dumps:
    path: /dumps
    weights: weights
    logs: logs

model: &model src.models.unet.ResnetSuperVision
model_params: &model_params
    seg_classes: 1
    backbone_arch: resnet34

train_params:
    name: resnet34_768_unet
    model: *model
    model_params: *model_params
    loss: src.losses.ComboSuperVisionLoss
    loss_params:
        weights:
            bce: 3
            dice: 1
        sv_weight: 0.1
    metrics:
        src.metrics.DiceMetric:
            score_threshold: 0.5

predict_params:
    model: *model
    model_params: *model_params

epochs: &epochs 60

data_params:
    data_folder: /data/input/dataset1024
    transform:
        train: /kaggle-pneumothorax/configs/train_transforms_768.yaml
        val: /kaggle-pneumothorax/configs/val_transforms_768.yaml
        test: /kaggle-pneumothorax/configs/val_transforms_768.yaml
    batch_size: 8
    num_workers: 8
    folds_path: /data/folds.csv
    positive_ratio_range: [0.22, 0.8]
    epochs: *epochs

stages:
    cosine:
        optimizer: Adam
        optimizer_params:
            lr: 0.000075
            weight_decay: 0.00001
        scheduler: CosineAnnealingLR
        scheduler_params:
            T_max: 8
            eta_min: 0.000001
        epochs: *epochs
