__version__: 0.3.1
transform:
  __class_fullname__: albumentations.core.composition.Compose
  p: 1
  transforms:
    -
      __class_fullname__: albumentations.augmentations.transforms.Resize
      always_apply: true
      p: 1
      height: 768
      width: 768
      interpolation: 1
    -
      __class_fullname__: albumentations.augmentations.transforms.Normalize
      always_apply: false
      p: 1
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225
      max_pixel_value: 255
  bbox_params: {}
  keypoint_params: {}
  additional_targets: {}
